baseURL: "https://okuryavuz.github.io/" 
title: Yavuz Selim Okur - Portfolio
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Games
          url: https://yavuzselimokur.itch.io/
          weight: 1 

params:
    description: "I am Yavuz Selim. I've been trying to improve myself in game design and game development since 2016."
    author: Yavuz Selim Okur
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: dark
    hideFooter: false
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["games"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Yavuz Selim Okur
          subtitle: "I am Yavuz Selim. I've been trying to improve myself in game design and game development since 2016. I have made a variety of games on Unity Engine and Unreal Engine. I hope to be a person that shape the game industry in the future."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Games
              url: https://yavuzselimokur.itch.io/
              weight: 1 

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:yavuzselimokur@gmail.com
        - name: itchio
          url: https://yavuzselimokur.itch.io/
        - name: linkedin
          url: https://www.linkedin.com/in/yavuz-selim-okur-8b6605164/

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Yavuz Selim Okur"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2